### ISSUE TITLE
weka version

### ISSUE THREAD

**Issue by julian-ramos** [Shookit/android-ml-weka#1]
Hi Shookit,

Thanks for sharing this code! question: Which version of Weka is this?

I checked on the folders and found that it is 3.4 but seems too old. 

Best,

**Comment by Shookit** [comment]
That's a great question... it was using the most recent version of Weka as of 2014/9/1. I believe this was 3.7, but I'm a bit rusty on this. If you need to build a new version for yourself, my procedure is in the README.md.
